### ISSUE TITLE
Unusable on dark L&F (UI)

### ISSUE THREAD

**Issue by tmysik** [OtterBrowser/otter-browser#1209]
When using dark L&F, some web pages cannot be used - their text in form fields is black on black background together with black buttons (again with black labels). See screenshot of this URL [1]:

![screenshot_20161022_143032](https://cloud.githubusercontent.com/assets/331924/19619309/6176f53e-9864-11e6-86f5-8cf2dceff375.png)

Note: Chrome displays the page properly.

Thanks.
[1] https://netbeans.org/bugzilla/show_bug.cgi?id=268447

**Comment by annulen** [comment]
What QtWebKit version is used?

**Comment by annulen** [comment]
Also, screenshot from Chrome (or any other browser, given that it picks colors from system theme) would be great for comparison

**Comment by tmysik** [comment]
@annulen 

> What QtWebKit version is used?

```Jádro WebKit (zastaralé) 538.1.```

(zastaralé = out of date)

Screenshot fro Chrome:

![screenshot_20161024_072610](https://cloud.githubusercontent.com/assets/331924/19634420/2f8e93f8-99bb-11e6-8e6b-88f4039090b2.png)


Thanks!

**Comment by annulen** [comment]
What is Qt version?

**Comment by tmysik** [comment]
@annulen 

> What is Qt version?

Otter browser says: ```Qt-verze 5.6.1```

Thanks.

**Comment by tmysik** [comment]
BTW I am on Kubuntu 16.10, if it helps.

**Comment by tmysik** [comment]
And my Otter version is:

```Otter 0.9.11 weekly 142```

Using weekly PPA.

Thanks!

**Comment by Emdek** [comment]
@tmysik, I've tested it and it turns out to be mix of bugs in theme of that page (they set color but not background, otherwise there would be contrast) plus QtWebKit ignoring user agent stylesheet.

User agent stylesheet:
```css
input, input[type="password"], input[type="search"], isindex {
-webkit-appearance: textfield;
padding: 1px;
background-color: white;
border: 2px inset;
border-image-source: initial;
border-image-slice: initial;
border-image-width: initial;
border-image-outset: initial;
border-image-repeat: initial;
-webkit-rtl-ordering: logical;
-webkit-user-select: text;
cursor: auto;
}
```

global.css:
```css
body, td, th, input {
color: #333333;
font-family: Verdana,"Verdana CE",Arial,"Arial CE","Lucida Grande CE",lucida,"Helvetica CE",sans-serif;
font-size: 1em;
}
```

There is no easy workaround for this, but you can try to use user stylesheet that sets text color to black and background to white, like:

```css
input, select, textarea
{
    background:#FFF;
    color:#000;
}
```
